
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.awt.event.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class AddPost extends javax.swing.JFrame {
    JFileChooser chooser;

    File f;

    /**
     * Creates new form AddPost
     */
    public AddPost() {
        initComponents();
        setSize(800,700);
    }
    
    String username;

    AddPost(String username) {
        initComponents();
        this.username = username;
        //System.out.println(username);
        setSize(800, 700);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        chooser=new JFileChooser();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        captionlb = new javax.swing.JLabel();
        photolb = new javax.swing.JLabel();
        choosebtn = new javax.swing.JButton();
        postlb = new javax.swing.JLabel();
        filter1btn = new javax.swing.JButton();
        filter2btn = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        captionta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        captionlb.setText("Caption");
        getContentPane().add(captionlb);
        captionlb.setBounds(110, 70, 120, 30);

        photolb.setText("Photo");
        getContentPane().add(photolb);
        photolb.setBounds(110, 130, 160, 50);

        choosebtn.setText("Choose");
        choosebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosebtnActionPerformed(evt);
            }
        });
        getContentPane().add(choosebtn);
        choosebtn.setBounds(290, 130, 110, 40);

        postlb.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(postlb);
        postlb.setBounds(130, 180, 330, 190);

        filter1btn.setText("Filter1");
        getContentPane().add(filter1btn);
        filter1btn.setBounds(490, 190, 100, 40);

        filter2btn.setText("Filter2");
        getContentPane().add(filter2btn);
        filter2btn.setBounds(490, 250, 100, 40);

        addbtn.setText("Post");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        getContentPane().add(addbtn);
        addbtn.setBounds(240, 390, 130, 40);

        jLabel4.setBackground(new java.awt.Color(255, 153, 153));
        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setText("ADD POST");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(250, 10, 190, 40);

        captionta.setColumns(20);
        captionta.setRows(5);
        jScrollPane1.setViewportView(captionta);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(240, 60, 260, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choosebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosebtnActionPerformed
       
        int r = chooser.showOpenDialog(this);
        if (r == JFileChooser.APPROVE_OPTION) {
            f = chooser.getSelectedFile();
            try {

                BufferedImage bimg = ImageIO.read(f);
                Image img = bimg.getScaledInstance(postlb.getWidth(), postlb.getHeight(), Image.SCALE_SMOOTH);
                postlb.setIcon(new ImageIcon(img));

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_choosebtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        try {
            String caption = captionta.getText();
            
            if (f == null) 
            {
                JOptionPane.showMessageDialog(this, "Please choose file");
            }
            
            else
            {
                HttpResponse<String> res = Unirest.post("http://localhost:8999/addpost")
                                      .queryString("caption",caption)
                                      .queryString("username",username)
                                      .field("photo", f)
                                      .asString();
                
                if(res.getStatus()==200)
                {
                    String pid = res.getBody();
                    System.out.println(pid);
                    JOptionPane.showMessageDialog(this, "Post Added");
                    new AddStory(pid,username).setVisible(true);
                }
            
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_addbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPost().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JLabel captionlb;
    private javax.swing.JTextArea captionta;
    private javax.swing.JButton choosebtn;
    private javax.swing.JButton filter1btn;
    private javax.swing.JButton filter2btn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel photolb;
    private javax.swing.JLabel postlb;
    // End of variables declaration//GEN-END:variables
}
