
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author DELL
 */
public class UserSignup extends javax.swing.JFrame {

    JFileChooser chooser;

    File f;

    public UserSignup() {
        initComponents();
        setSize(800, 700);
        gendercb.removeAllItems();
        gendercb.addItem("Male");
        gendercb.addItem("Female");
        chooser=new JFileChooser();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernametf1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        passwordtf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        phonenotf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        imgbtn = new javax.swing.JButton();
        singupbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        emailtf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        gendercb = new javax.swing.JComboBox<>();
        photolb = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dispnametf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("SIGNUP");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 10, 130, 40);

        jLabel3.setText("Enter Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 60, 170, 30);
        getContentPane().add(usernametf1);
        usernametf1.setBounds(310, 50, 200, 30);

        jLabel4.setText("Enter password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 150, 170, 30);
        getContentPane().add(passwordtf);
        passwordtf.setBounds(310, 150, 200, 30);

        jLabel5.setText("Enter Phoneno");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 200, 170, 30);
        getContentPane().add(phonenotf);
        phonenotf.setBounds(310, 200, 200, 30);

        jLabel2.setText("Choose Photo");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 350, 170, 30);

        imgbtn.setText("Choose");
        imgbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imgbtnActionPerformed(evt);
            }
        });
        getContentPane().add(imgbtn);
        imgbtn.setBounds(310, 350, 140, 30);

        singupbtn.setText("SINGUP");
        singupbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singupbtnActionPerformed(evt);
            }
        });
        getContentPane().add(singupbtn);
        singupbtn.setBounds(210, 410, 190, 50);

        jLabel6.setText("Enter Email");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 300, 170, 30);
        getContentPane().add(emailtf);
        emailtf.setBounds(310, 250, 200, 30);

        jLabel7.setText("Enter Email");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 250, 170, 30);

        gendercb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(gendercb);
        gendercb.setBounds(310, 300, 200, 30);

        photolb.setText("jLabel8");
        getContentPane().add(photolb);
        photolb.setBounds(490, 350, 80, 60);

        jLabel8.setText("Enter Display Name");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 110, 170, 30);
        getContentPane().add(dispnametf);
        dispnametf.setBounds(310, 100, 200, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imgbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imgbtnActionPerformed

        int r = chooser.showOpenDialog(this);
        if (r == JFileChooser.APPROVE_OPTION) {
            f = chooser.getSelectedFile();
            try {

                BufferedImage bimg = ImageIO.read(f);
                Image img = bimg.getScaledInstance(photolb.getWidth(), photolb.getHeight(), Image.SCALE_SMOOTH);
                photolb.setIcon(new ImageIcon(img));

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_imgbtnActionPerformed

    private void singupbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singupbtnActionPerformed

        try {

            String username = usernametf1.getText();
            String dispname = dispnametf.getText();
            String password = passwordtf.getText();
            String email = emailtf.getText();
            String phoneno = phonenotf.getText();
            String gender = gendercb.getSelectedItem().toString();

            if (username.equals("") || password.equals("") || email.equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter values");
            } 
            else if (f == null) 
            {
                JOptionPane.showMessageDialog(this, "Please choose file");
            }
            else if(phoneno.length()!=10)
                {
                    JOptionPane.showMessageDialog(this,"Number is Inavalid");
                }
            else if(email.endsWith("@gmail.com"))
            {
                HttpResponse<String> res = Unirest.post("http://localhost:8999/usersignup")
                        .queryString("username", username)
                        .queryString("displayname", dispname)
                        .queryString("password", password)
                        .queryString("email", email)
                        .queryString("gender", gender)
                        .queryString("phoneno", phoneno)
                        .field("photo", f)
                        .asString();

                if (res.getStatus() == 200) {
                    JOptionPane.showMessageDialog(this, res.getBody());
                    
                    String responsetext = res.getBody();
                    if (responsetext.equals("success")) {

                        new UserLogin().setVisible(true);
                        dispose();
                    } else {

                    }
                }

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_singupbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserSignup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dispnametf;
    private javax.swing.JTextField emailtf;
    private javax.swing.JComboBox<String> gendercb;
    private javax.swing.JButton imgbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField passwordtf;
    private javax.swing.JTextField phonenotf;
    private javax.swing.JLabel photolb;
    private javax.swing.JButton singupbtn;
    private javax.swing.JTextField usernametf1;
    // End of variables declaration//GEN-END:variables
}
